### ISSUE TITLE
工具做的不错

### ISSUE THREAD

**Issue by kvell0628** [188080501/JQTools#10]
为小软件开发解决了很多实际问题，还节约了时间，值得鼓励，之后可否改成插件式的功能开发，这样就可以方便的进行功能复用了

**Comment by 188080501** [comment]
目前代码上，不同的功能已经被拆分在components里面，并基于文件结构做了分类。
比如说大小写切换，就在JQTools/components/TextGroup/CaseTransform里面，所有的C++代码和QML代码都在这一个文件夹里，并且已经写了pri可以直接导入。
另外还有一个基类，在JQTools/lib/JQToolsLibrary里面

**Comment by kvell0628** [comment]
good

**Comment by kvell0628** [comment]
今天换mac编译了一下，发现一个问题：Undefined symbols for architecture x86_64:"JQGuetzli::process(QString const&, QString const&)"
qt版本:5.8.0 
Xcode:Version 8.3.3

**Comment by 188080501** [comment]
Mac下依赖Guetzli，需要自己配置一下环境

**Comment by 188080501** [comment]
或者我去改下，如果没这个环境，我就不导入JPG压缩模块了

**Comment by kvell0628** [comment]
ok，知道了，我配置一下试试

**Comment by kvell0628** [comment]
找了一下，不知道怎么配置，能否配置一个没有JPG压缩模块的工程呢？我clone一下？多谢

**Comment by 188080501** [comment]
你删掉这里的文件
JQTools/components/ToolsGroup/JpgOptimize

另外把JQLibraryImport.pri中的include( $$PWD/lib/JQLibrary/JQZopfli.pri )去掉

**Comment by kvell0628** [comment]
我把JpgOptimize去掉了，没有找到JQLibraryImport.pri，But it works well! good!
