### ISSUE TITLE
TypeError: Type error

### ISSUE THREAD

**Issue by wentaojia2014** [188080501/JQTools#11]
我在 点击 ‘JPG图像压缩’的时候有个错误：
qrc:/main.qml:444: TypeError: Type error

我的环境：
Ubuntu 16.04 64bit, 
Qt5.9.0
debug | release模式都有

git commit hash： 0c293ad4ead5285e41dab5799c21f3540d0bb971

**Comment by 188080501** [comment]
目前JPG图像压缩模式只在macOS下有效。Windows和Linux无法使用。
原因是缺少Guetzli库，这个库需要自己编译。
