### ISSUE TITLE
兄弟，最近我的项目里又这个警告libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by xiedonghuilove** [188080501/JQTools#12]
我想知道这部分的功能代码是怎么实现的。感谢！

**Comment by 188080501** [comment]
请参考代码：
https://github.com/188080501/JQTools/blob/master/components/QtGroup/PngWarningRemover/cpp/pngwarningremover.cpp

本质上就是把图片用QImage读取一下，然后再save
