### ISSUE TITLE
PropertyMaker 建议

### ISSUE THREAD

**Issue by qyvlik** [188080501/JQTools#2]
`JQTools/Groups/Qt/PropertyMaker/qml/PropertyMaker.qml` 中，TextEdit 设置 `TextEdit::selectByMouse` 为 true。才可用鼠标选择文本。

**Comment by 188080501** [comment]
的确，用鼠标不能选中内容。因为我一直使用全选快捷键，所以没注意到这个。我去修复下。感谢建议

**Comment by qyvlik** [comment]
@188080501  其他有用到 `TextEdit` 的地方都可以考虑设置一下。

**Comment by 188080501** [comment]
恩，4个地方，都改好了。

**Comment by 188080501** [comment]
代码已经提交了，二进制先不发布，等下一轮更新。
