### ISSUE TITLE
感谢大佬，最近的release里没有最新的win下编译好的文件么？

### ISSUE THREAD

**Issue by 3xxx** [188080501/JQTools#21]
大佬，能否抽空编译一下放release里啊？呵呵。感谢。好多功能太需要了。

**Comment by 188080501** [comment]
没有大更新，所以一直没重新编译。之前版本也能用的啊，你这边需要最新的exe吗？

**Comment by 3xxx** [comment]
嗯，想试试新版的。现在这版在某些电脑上无法运行。笔记本电脑可以运行。
![Snap1](https://user-images.githubusercontent.com/10678867/59272846-7605a380-8c89-11e9-9dbc-229a033c0e0f.png)

**Comment by 188080501** [comment]
这个打包的程序在远程桌面，或者缺乏GPU设备情况下，都无法运行

**Comment by 3xxx** [comment]
哦，好的，谢谢。
