### ISSUE TITLE
寻求商务合作

### ISSUE THREAD

**Issue by specialzxw** [188080501/JQTools#27]
hi，我们对您分享的这个项目十分感兴趣，您的专业技术十分出色，我们想与您进行商务合作，但是github上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系吗？

**Comment by 188080501** [comment]
Hi
感谢来信，我的微信号和这个邮箱一样是188080501




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "188080501/JQTools"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月3日(星期四) 下午5:54
收件人:&nbsp;"188080501/JQTools"<JQTools@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[188080501/JQTools] 寻求商务合作 (#27)





 
hi，我们对您分享的这个项目十分感兴趣，您的专业技术十分出色，我们想与您进行商务合作，但是github上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系吗？

**Comment by 188080501** [comment]
Hi
可以添加188080501微信

**Comment by specialzxw** [comment]
hi，已经添加您了～
