### ISSUE TITLE
qt5.9 编译问题

### ISSUE THREAD

**Issue by Siberia-yuan** [188080501/JQTools#30]
在iconmaker.cpp 文件中的
void Manage::saveToEmptyPng(const QString &targetFilePath, const QSize &size)函数里 image.sizeInBytes() 在qt5.9无法通过编译， 我查了一下QImage::sizeInByte() 本身是在qt 5.10 才引入的函数，5.9之前这个函数是没有的

**Comment by 188080501** [comment]
https://github.com/188080501/JQTools/commit/3377cc22870788a0b1ecee61f6761627be592206

**Comment by 188080501** [comment]
感谢反馈，已修复
