### ISSUE TITLE
qrc加载qml资源问题

### ISSUE THREAD

**Issue by jick401** [188080501/JQTools#33]
您好，非常感谢分享这个功能强大的JQTOOl工具，我想借鉴下大牛的工程结构，有个问题困惑了我很久，为什么在MaterialUI问价夹下只有您创建的qml文件可以有联想及高亮功能，为什么我在相同路径中创建的qml文件，只会提示报错，没有办法高亮及联想呢？是我版本的问题吗？

**Comment by 188080501** [comment]
需要配置qmldir

**Comment by 188080501** [comment]
参考下qmldir里面格式，跟着修改下。
另外有时候QtCreator有bug不能正常识别，重启下QtCreator才能恢复正常
