### ISSUE TITLE
编译有点小错误

### ISSUE THREAD

**Issue by LmyPotato** [188080501/JQTools#39]
:-1: error: [debug/JQTools_resource_res.o] Error 1
使用的版本是Qt5.9

**Comment by 188080501** [comment]
可以换高版本Qt试一下不
另外你用的具体环境是什么？win？

**Comment by LmyPotato** [comment]
可以了，换个高一点的版本就好了



| |
lmypotato
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月23日 21:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [188080501/JQTools] 编译有点小错误 (Issue #39) |

可以换高版本Qt试一下不
另外你用的具体环境是什么？win？

**Comment by 188080501** [comment]
好的，有问题再反馈，本issues关闭
