### ISSUE TITLE
qml文件

### ISSUE THREAD

**Issue by caol66** [188080501/JQTools#44]
请教大佬 MaterialUI下面的qml文件是从什么库获取的吗？想从源头学习一下

**Comment by 188080501** [comment]
https://github.com/papyros/qml-material/tree/develop
可以看下这里，但是现在官方已经支持的比较好了，不建议再用第三方库

**Comment by caol66** [comment]
收到啦，非常感谢您的回复-------- 原始邮件 --------发件人： Jason ***@***.***>日期： 2024年2月1日周四 15:43收件人： 188080501/JQTools ***@***.***>抄送： caol66 ***@***.***>, Author ***@***.***>主    题： Re: [188080501/JQTools] qml文件 (Issue #44)
https://github.com/papyros/qml-material/tree/develop
可以看下这里，但是现在官方已经支持的比较好了，不建议再用第三方库
