### ISSUE TITLE
图片压缩功能bug

### ISSUE THREAD

**Issue by qyvlik** [188080501/JQTools#6]
选中一张png。进行压缩，然后选中 **另存为优化图片到桌面**，运行，然后桌面只有文件夹，没有优化的图片。

**Comment by 188080501** [comment]
能不能把你用的PNG图片发我下

**Comment by 188080501** [comment]
<img width="1173" alt="2016-08-03 8 08 26" src="https://cloud.githubusercontent.com/assets/6997074/17349566/89ceeb6a-5951-11e6-9afc-b33e5b299cf9.png">

我测试了GitHub中release里的那个版本，是没问题的，我怀疑和图片有关

**Comment by qyvlik** [comment]
@188080501  我把图片发到你的邮箱了~

**Comment by 188080501** [comment]
我在macOS下测试，是正常的，等会到Windows下试试

**Comment by 188080501** [comment]
`
<img width="646" alt="2016-08-04 10 01 25" src="https://cloud.githubusercontent.com/assets/6997074/17387892/7113e394-5a2a-11e6-8484-7d5662652698.png">
`

这是在Windows下，压缩图片的结果，也是正常的
