### ISSUE TITLE
朋友能否增加一个功能qss处理的

### ISSUE THREAD

**Issue by ver007** [188080501/JQTools#8]
每次更改界面qss文件的时候就很费劲

**Comment by 188080501** [comment]
请问大约是那个方面的需求呢？

**Comment by 188080501** [comment]
具体一点的

**Comment by ver007** [comment]
朋友实在不好意思,现在才看到, 上次说的增加一个qss设计预览软件 ,大概是这样一个需求
左边是一个qss编辑器，右边显示所有控件qss 样式后的结果,
选中一段qss , 同样在控件上做圈识 ,这样就可以很方便的查看qss和设计qss了

**Comment by 188080501** [comment]
这个功能的话，现在QtCreator就有啊，而且更加完善
